// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/api/concert/v1/catalog.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListConcertParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint64                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	ListMask      *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=list_mask,json=listMask,proto3" json:"list_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConcertParam) Reset() {
	*x = ListConcertParam{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConcertParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConcertParam) ProtoMessage() {}

func (x *ListConcertParam) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConcertParam.ProtoReflect.Descriptor instead.
func (*ListConcertParam) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ListConcertParam) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConcertParam) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListConcertParam) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListConcertParam) GetListMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ListMask
	}
	return nil
}

type ListConcertsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concerts      []*Concert             `protobuf:"bytes,1,rep,name=concerts,proto3" json:"concerts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConcertsResult) Reset() {
	*x = ListConcertsResult{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConcertsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConcertsResult) ProtoMessage() {}

func (x *ListConcertsResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConcertsResult.ProtoReflect.Descriptor instead.
func (*ListConcertsResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListConcertsResult) GetConcerts() []*Concert {
	if x != nil {
		return x.Concerts
	}
	return nil
}

func (x *ListConcertsResult) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetConcertParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concert       string                 `protobuf:"bytes,1,opt,name=concert,proto3" json:"concert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConcertParam) Reset() {
	*x = GetConcertParam{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConcertParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConcertParam) ProtoMessage() {}

func (x *GetConcertParam) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConcertParam.ProtoReflect.Descriptor instead.
func (*GetConcertParam) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetConcertParam) GetConcert() string {
	if x != nil {
		return x.Concert
	}
	return ""
}

type GetConcertResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concert       *Concert               `protobuf:"bytes,1,opt,name=concert,proto3" json:"concert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConcertResult) Reset() {
	*x = GetConcertResult{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConcertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConcertResult) ProtoMessage() {}

func (x *GetConcertResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConcertResult.ProtoReflect.Descriptor instead.
func (*GetConcertResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetConcertResult) GetConcert() *Concert {
	if x != nil {
		return x.Concert
	}
	return nil
}

type Concert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConcertId     string                 `protobuf:"bytes,2,opt,name=concert_id,json=concertId,proto3" json:"concert_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Performers    []*Performer           `protobuf:"bytes,5,rep,name=performers,proto3" json:"performers,omitempty"`
	AnnouncedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=announced_at,json=announcedAt,proto3" json:"announced_at,omitempty"`
	Shows         []*Show                `protobuf:"bytes,7,rep,name=shows,proto3" json:"shows,omitempty"`
	TicketPrice   *TicketPrice           `protobuf:"bytes,8,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Concert) Reset() {
	*x = Concert{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concert) ProtoMessage() {}

func (x *Concert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concert.ProtoReflect.Descriptor instead.
func (*Concert) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *Concert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Concert) GetConcertId() string {
	if x != nil {
		return x.ConcertId
	}
	return ""
}

func (x *Concert) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Concert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Concert) GetPerformers() []*Performer {
	if x != nil {
		return x.Performers
	}
	return nil
}

func (x *Concert) GetAnnouncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnnouncedAt
	}
	return nil
}

func (x *Concert) GetShows() []*Show {
	if x != nil {
		return x.Shows
	}
	return nil
}

func (x *Concert) GetTicketPrice() *TicketPrice {
	if x != nil {
		return x.TicketPrice
	}
	return nil
}

type Show struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShowId           string                 `protobuf:"bytes,2,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	Concert          string                 `protobuf:"bytes,3,opt,name=concert,proto3" json:"concert,omitempty"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Venue            string                 `protobuf:"bytes,6,opt,name=venue,proto3" json:"venue,omitempty"`
	MaxCapacity      int32                  `protobuf:"varint,7,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	AvailableTickets int32                  `protobuf:"varint,8,opt,name=available_tickets,json=availableTickets,proto3" json:"available_tickets,omitempty"`
	TicketPrice      *TicketPrice           `protobuf:"bytes,9,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Show) Reset() {
	*x = Show{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Show) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Show) ProtoMessage() {}

func (x *Show) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Show.ProtoReflect.Descriptor instead.
func (*Show) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Show) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Show) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *Show) GetConcert() string {
	if x != nil {
		return x.Concert
	}
	return ""
}

func (x *Show) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Show) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Show) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *Show) GetMaxCapacity() int32 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *Show) GetAvailableTickets() int32 {
	if x != nil {
		return x.AvailableTickets
	}
	return 0
}

func (x *Show) GetTicketPrice() *TicketPrice {
	if x != nil {
		return x.TicketPrice
	}
	return nil
}

type Performer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Genres        []string               `protobuf:"bytes,3,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Performer) Reset() {
	*x = Performer{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Performer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Performer) ProtoMessage() {}

func (x *Performer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Performer.ProtoReflect.Descriptor instead.
func (*Performer) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *Performer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Performer) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Performer) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type TicketPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketPrice) Reset() {
	*x = TicketPrice{}
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketPrice) ProtoMessage() {}

func (x *TicketPrice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_concert_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketPrice.ProtoReflect.Descriptor instead.
func (*TicketPrice) Descriptor() ([]byte, []int) {
	return file_pkg_api_concert_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *TicketPrice) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TicketPrice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_pkg_api_concert_v1_catalog_proto protoreflect.FileDescriptor

const file_pkg_api_concert_v1_catalog_proto_rawDesc = "" +
	"\n" +
	" pkg/api/concert/v1/catalog.proto\x12\x16example.com.concert.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17google/api/client.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/field_mask.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x10ListConcertParam\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x04R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x127\n" +
	"\tlist_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\blistMask\"y\n" +
	"\x12ListConcertsResult\x12;\n" +
	"\bconcerts\x18\x01 \x03(\v2\x1f.example.com.concert.v1.ConcertR\bconcerts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"P\n" +
	"\x0fGetConcertParam\x12=\n" +
	"\aconcert\x18\x01 \x01(\tB#\xe0A\x02\xfaA\x1d\n" +
	"\x1bconcert.example.com/ConcertR\aconcert\"M\n" +
	"\x10GetConcertResult\x129\n" +
	"\aconcert\x18\x01 \x01(\v2\x1f.example.com.concert.v1.ConcertR\aconcert\"\xd2\x03\n" +
	"\aConcert\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\"\n" +
	"\n" +
	"concert_id\x18\x02 \x01(\tB\x03\xe0A\x03R\tconcertId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12A\n" +
	"\n" +
	"performers\x18\x05 \x03(\v2!.example.com.concert.v1.PerformerR\n" +
	"performers\x12=\n" +
	"\fannounced_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vannouncedAt\x122\n" +
	"\x05shows\x18\a \x03(\v2\x1c.example.com.concert.v1.ShowR\x05shows\x12F\n" +
	"\fticket_price\x18\b \x01(\v2#.example.com.concert.v1.TicketPriceR\vticketPrice:G\xeaAD\n" +
	"\x1bconcert.example.com/Concert\x12\x12concerts/{concert}*\bconcerts2\aconcert\"\xe0\x03\n" +
	"\x04Show\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1c\n" +
	"\ashow_id\x18\x02 \x01(\tB\x03\xe0A\x03R\x06showId\x12:\n" +
	"\aconcert\x18\x03 \x01(\tB \xfaA\x1d\n" +
	"\x1bconcert.example.com/ConcertR\aconcert\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05venue\x18\x06 \x01(\tR\x05venue\x12!\n" +
	"\fmax_capacity\x18\a \x01(\x05R\vmaxCapacity\x12+\n" +
	"\x11available_tickets\x18\b \x01(\x05R\x10availableTickets\x12F\n" +
	"\fticket_price\x18\t \x01(\v2#.example.com.concert.v1.TicketPriceR\vticketPrice:E\xeaAB\n" +
	"\x1fconcert.example.com/ConcertShow\x12\x1fconcerts/{concert}/shows/{show}\"T\n" +
	"\tPerformer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x16\n" +
	"\x06genres\x18\x03 \x03(\tR\x06genres\"?\n" +
	"\vTicketPrice\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency2\xd3\x02\n" +
	"\x0eCatalogService\x12\x98\x01\n" +
	"\fListConcerts\x12(.example.com.concert.v1.ListConcertParam\x1a*.example.com.concert.v1.ListConcertsResult\"2\x92A\x0f\x12\rList Concerts\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/concert/v1/concerts\x12\xa5\x01\n" +
	"\n" +
	"GetConcert\x12'.example.com.concert.v1.GetConcertParam\x1a(.example.com.concert.v1.GetConcertResult\"D\x92A\r\x12\vGet Concert\xdaA\aconcert\x82\xd3\xe4\x93\x02$\x12\"/api/concert/v1/concerts/{concert}B Z\x1eexample.com/pkg/api/concert/v1b\x06proto3"

var (
	file_pkg_api_concert_v1_catalog_proto_rawDescOnce sync.Once
	file_pkg_api_concert_v1_catalog_proto_rawDescData []byte
)

func file_pkg_api_concert_v1_catalog_proto_rawDescGZIP() []byte {
	file_pkg_api_concert_v1_catalog_proto_rawDescOnce.Do(func() {
		file_pkg_api_concert_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_concert_v1_catalog_proto_rawDesc), len(file_pkg_api_concert_v1_catalog_proto_rawDesc)))
	})
	return file_pkg_api_concert_v1_catalog_proto_rawDescData
}

var file_pkg_api_concert_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_api_concert_v1_catalog_proto_goTypes = []any{
	(*ListConcertParam)(nil),      // 0: example.com.concert.v1.ListConcertParam
	(*ListConcertsResult)(nil),    // 1: example.com.concert.v1.ListConcertsResult
	(*GetConcertParam)(nil),       // 2: example.com.concert.v1.GetConcertParam
	(*GetConcertResult)(nil),      // 3: example.com.concert.v1.GetConcertResult
	(*Concert)(nil),               // 4: example.com.concert.v1.Concert
	(*Show)(nil),                  // 5: example.com.concert.v1.Show
	(*Performer)(nil),             // 6: example.com.concert.v1.Performer
	(*TicketPrice)(nil),           // 7: example.com.concert.v1.TicketPrice
	(*fieldmaskpb.FieldMask)(nil), // 8: google.protobuf.FieldMask
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_pkg_api_concert_v1_catalog_proto_depIdxs = []int32{
	8,  // 0: example.com.concert.v1.ListConcertParam.list_mask:type_name -> google.protobuf.FieldMask
	4,  // 1: example.com.concert.v1.ListConcertsResult.concerts:type_name -> example.com.concert.v1.Concert
	4,  // 2: example.com.concert.v1.GetConcertResult.concert:type_name -> example.com.concert.v1.Concert
	6,  // 3: example.com.concert.v1.Concert.performers:type_name -> example.com.concert.v1.Performer
	9,  // 4: example.com.concert.v1.Concert.announced_at:type_name -> google.protobuf.Timestamp
	5,  // 5: example.com.concert.v1.Concert.shows:type_name -> example.com.concert.v1.Show
	7,  // 6: example.com.concert.v1.Concert.ticket_price:type_name -> example.com.concert.v1.TicketPrice
	9,  // 7: example.com.concert.v1.Show.start_time:type_name -> google.protobuf.Timestamp
	9,  // 8: example.com.concert.v1.Show.end_time:type_name -> google.protobuf.Timestamp
	7,  // 9: example.com.concert.v1.Show.ticket_price:type_name -> example.com.concert.v1.TicketPrice
	0,  // 10: example.com.concert.v1.CatalogService.ListConcerts:input_type -> example.com.concert.v1.ListConcertParam
	2,  // 11: example.com.concert.v1.CatalogService.GetConcert:input_type -> example.com.concert.v1.GetConcertParam
	1,  // 12: example.com.concert.v1.CatalogService.ListConcerts:output_type -> example.com.concert.v1.ListConcertsResult
	3,  // 13: example.com.concert.v1.CatalogService.GetConcert:output_type -> example.com.concert.v1.GetConcertResult
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_api_concert_v1_catalog_proto_init() }
func file_pkg_api_concert_v1_catalog_proto_init() {
	if File_pkg_api_concert_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_concert_v1_catalog_proto_rawDesc), len(file_pkg_api_concert_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_concert_v1_catalog_proto_goTypes,
		DependencyIndexes: file_pkg_api_concert_v1_catalog_proto_depIdxs,
		MessageInfos:      file_pkg_api_concert_v1_catalog_proto_msgTypes,
	}.Build()
	File_pkg_api_concert_v1_catalog_proto = out.File
	file_pkg_api_concert_v1_catalog_proto_goTypes = nil
	file_pkg_api_concert_v1_catalog_proto_depIdxs = nil
}
