// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/api/course/v1/catalog.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Instructors   []*Instructor          `protobuf:"bytes,5,rep,name=instructors,proto3" json:"instructors,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Batches       []*Batch               `protobuf:"bytes,7,rep,name=batches,proto3" json:"batches,omitempty"`
	Price         *Price                 `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_pkg_api_course_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Course) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetInstructors() []*Instructor {
	if x != nil {
		return x.Instructors
	}
	return nil
}

func (x *Course) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Course) GetBatches() []*Batch {
	if x != nil {
		return x.Batches
	}
	return nil
}

func (x *Course) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type Instructor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instructor) Reset() {
	*x = Instructor{}
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instructor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instructor) ProtoMessage() {}

func (x *Instructor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instructor.ProtoReflect.Descriptor instead.
func (*Instructor) Descriptor() ([]byte, []int) {
	return file_pkg_api_course_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Instructor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instructor) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Instructor) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Batch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BatchId        string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Course         string                 `protobuf:"bytes,4,opt,name=course,proto3" json:"course,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	MaxSeats       int32                  `protobuf:"varint,7,opt,name=max_seats,json=maxSeats,proto3" json:"max_seats,omitempty"`
	AvailableSeats int32                  `protobuf:"varint,8,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	Price          *Price                 `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_pkg_api_course_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Batch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Batch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Batch) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Batch) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *Batch) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Batch) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Batch) GetMaxSeats() int32 {
	if x != nil {
		return x.MaxSeats
	}
	return 0
}

func (x *Batch) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *Batch) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_pkg_api_course_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Price) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Price) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ListCoursesParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint64                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	ListMask      *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=list_mask,json=listMask,proto3" json:"list_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesParam) Reset() {
	*x = ListCoursesParam{}
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesParam) ProtoMessage() {}

func (x *ListCoursesParam) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesParam.ProtoReflect.Descriptor instead.
func (*ListCoursesParam) Descriptor() ([]byte, []int) {
	return file_pkg_api_course_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListCoursesParam) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCoursesParam) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCoursesParam) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListCoursesParam) GetListMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ListMask
	}
	return nil
}

type ListCoursesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesResult) Reset() {
	*x = ListCoursesResult{}
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesResult) ProtoMessage() {}

func (x *ListCoursesResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesResult.ProtoReflect.Descriptor instead.
func (*ListCoursesResult) Descriptor() ([]byte, []int) {
	return file_pkg_api_course_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListCoursesResult) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *ListCoursesResult) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetCourseParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        string                 `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseParam) Reset() {
	*x = GetCourseParam{}
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseParam) ProtoMessage() {}

func (x *GetCourseParam) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_course_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseParam.ProtoReflect.Descriptor instead.
func (*GetCourseParam) Descriptor() ([]byte, []int) {
	return file_pkg_api_course_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetCourseParam) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

var File_pkg_api_course_v1_catalog_proto protoreflect.FileDescriptor

const file_pkg_api_course_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/api/course/v1/catalog.proto\x12\x15example.com.course.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17google/api/client.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/field_mask.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x03\n" +
	"\x06Course\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12 \n" +
	"\tcourse_id\x18\x02 \x01(\tB\x03\xe0A\x03R\bcourseId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12C\n" +
	"\vinstructors\x18\x05 \x03(\v2!.example.com.course.v1.InstructorR\vinstructors\x12=\n" +
	"\fpublished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x126\n" +
	"\abatches\x18\a \x03(\v2\x1c.example.com.course.v1.BatchR\abatches\x122\n" +
	"\x05price\x18\b \x01(\v2\x1c.example.com.course.v1.PriceR\x05price:A\xeaA>\n" +
	"\x19course.example.com/Course\x12\x10courses/{course}*\acourses2\x06course\"S\n" +
	"\n" +
	"Instructor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"\xce\x03\n" +
	"\x05Batch\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1e\n" +
	"\bbatch_id\x18\x02 \x01(\tB\x03\xe0A\x03R\abatchId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x126\n" +
	"\x06course\x18\x04 \x01(\tB\x1e\xfaA\x1b\n" +
	"\x19course.example.com/CourseR\x06course\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1b\n" +
	"\tmax_seats\x18\a \x01(\x05R\bmaxSeats\x12'\n" +
	"\x0favailable_seats\x18\b \x01(\x05R\x0eavailableSeats\x122\n" +
	"\x05price\x18\t \x01(\v2\x1c.example.com.course.v1.PriceR\x05price:E\xeaAB\n" +
	"\x1ecourse.example.com/CourseBatch\x12 courses/{course}/batches/{batch}\"9\n" +
	"\x05Price\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xa2\x01\n" +
	"\x10ListCoursesParam\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x04R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x127\n" +
	"\tlist_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\blistMask\"t\n" +
	"\x11ListCoursesResult\x127\n" +
	"\acourses\x18\x01 \x03(\v2\x1d.example.com.course.v1.CourseR\acourses\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"K\n" +
	"\x0eGetCourseParam\x129\n" +
	"\x06course\x18\x01 \x01(\tB!\xe0A\x02\xfaA\x1b\n" +
	"\x19course.example.com/CourseR\x06course2\xb9\x02\n" +
	"\x0eCatalogService\x12\x91\x01\n" +
	"\vListCourses\x12'.example.com.course.v1.ListCoursesParam\x1a(.example.com.course.v1.ListCoursesResult\"/\x92A\x0e\x12\fList Courses\x82\xd3\xe4\x93\x02\x18\x12\x16/api/course/v1/courses\x12\x92\x01\n" +
	"\tGetCourse\x12%.example.com.course.v1.GetCourseParam\x1a\x1d.example.com.course.v1.Course\"?\x92A\f\x12\n" +
	"Get Course\xdaA\x06course\x82\xd3\xe4\x93\x02!\x12\x1f/api/course/v1/courses/{course}B\x1fZ\x1dexample.com/pkg/api/course/v1b\x06proto3"

var (
	file_pkg_api_course_v1_catalog_proto_rawDescOnce sync.Once
	file_pkg_api_course_v1_catalog_proto_rawDescData []byte
)

func file_pkg_api_course_v1_catalog_proto_rawDescGZIP() []byte {
	file_pkg_api_course_v1_catalog_proto_rawDescOnce.Do(func() {
		file_pkg_api_course_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_course_v1_catalog_proto_rawDesc), len(file_pkg_api_course_v1_catalog_proto_rawDesc)))
	})
	return file_pkg_api_course_v1_catalog_proto_rawDescData
}

var file_pkg_api_course_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_api_course_v1_catalog_proto_goTypes = []any{
	(*Course)(nil),                // 0: example.com.course.v1.Course
	(*Instructor)(nil),            // 1: example.com.course.v1.Instructor
	(*Batch)(nil),                 // 2: example.com.course.v1.Batch
	(*Price)(nil),                 // 3: example.com.course.v1.Price
	(*ListCoursesParam)(nil),      // 4: example.com.course.v1.ListCoursesParam
	(*ListCoursesResult)(nil),     // 5: example.com.course.v1.ListCoursesResult
	(*GetCourseParam)(nil),        // 6: example.com.course.v1.GetCourseParam
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 8: google.protobuf.FieldMask
}
var file_pkg_api_course_v1_catalog_proto_depIdxs = []int32{
	1,  // 0: example.com.course.v1.Course.instructors:type_name -> example.com.course.v1.Instructor
	7,  // 1: example.com.course.v1.Course.published_at:type_name -> google.protobuf.Timestamp
	2,  // 2: example.com.course.v1.Course.batches:type_name -> example.com.course.v1.Batch
	3,  // 3: example.com.course.v1.Course.price:type_name -> example.com.course.v1.Price
	7,  // 4: example.com.course.v1.Batch.start_date:type_name -> google.protobuf.Timestamp
	7,  // 5: example.com.course.v1.Batch.end_date:type_name -> google.protobuf.Timestamp
	3,  // 6: example.com.course.v1.Batch.price:type_name -> example.com.course.v1.Price
	8,  // 7: example.com.course.v1.ListCoursesParam.list_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: example.com.course.v1.ListCoursesResult.courses:type_name -> example.com.course.v1.Course
	4,  // 9: example.com.course.v1.CatalogService.ListCourses:input_type -> example.com.course.v1.ListCoursesParam
	6,  // 10: example.com.course.v1.CatalogService.GetCourse:input_type -> example.com.course.v1.GetCourseParam
	5,  // 11: example.com.course.v1.CatalogService.ListCourses:output_type -> example.com.course.v1.ListCoursesResult
	0,  // 12: example.com.course.v1.CatalogService.GetCourse:output_type -> example.com.course.v1.Course
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_api_course_v1_catalog_proto_init() }
func file_pkg_api_course_v1_catalog_proto_init() {
	if File_pkg_api_course_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_course_v1_catalog_proto_rawDesc), len(file_pkg_api_course_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_course_v1_catalog_proto_goTypes,
		DependencyIndexes: file_pkg_api_course_v1_catalog_proto_depIdxs,
		MessageInfos:      file_pkg_api_course_v1_catalog_proto_msgTypes,
	}.Build()
	File_pkg_api_course_v1_catalog_proto = out.File
	file_pkg_api_course_v1_catalog_proto_goTypes = nil
	file_pkg_api_course_v1_catalog_proto_depIdxs = nil
}
